<a href="https://colab.research.google.com/github/Jaleeza0625/Ever-Up-Data-Analytics-Micro-Credential-course/blob/main/Copy_of_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [ ]:
import numpy as np
# import numpy and labeled it np

#### Create an array of 20 zeros 

In [ ]:
np.zeros(20)
# I created an array of list of 20 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)
# I created an array of a list of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
np.ones(10)*5
# created an array of a list of 10 ones and multiple all the values by 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,50)
# I created an array of numbers with a range between 10 and 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,50,2)
# I created an array of numbers with a range between 10 and 50, divisible by 2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix=np.arange(0,9)
#created an array that list the values between 0 and 8( including 0 and 8)
matrix.reshape(3,3)
# reshaped the matrix to 3 list with 3 values in each

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)
#I created a matrix that has 3 list with 3 values in each with the value on the main diagonal.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)
# I created an array with an random number between 0 and 1


array([0.0801667])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.rand(25)
# I created an array of 25 numbers between 0 and 1

array([0.71610457, 0.17059438, 0.66308788, 0.3048976 , 0.09837264,
       0.01350632, 0.46597694, 0.53321262, 0.71706837, 0.07606104,
       0.03581734, 0.94256208, 0.49783081, 0.62221374, 0.9582946 ,
       0.52544769, 0.89176498, 0.57607419, 0.86264571, 0.56342562,
       0.82667931, 0.59685398, 0.19083616, 0.24683012, 0.44572539])

#### Create the following matrix:

In [ ]:
np.arange(0.01,1.01,.01).reshape(10,10)
# i created a matrix between 0.01 and 1.01, with increments of .01
# I reshaped the matrix to be 10 list with 10 values in each list

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.random.rand(20)
# I created an array of 25 numbers between 0 and 1

array([0.1391416 , 0.55619301, 0.57108007, 0.15376128, 0.78416803,
       0.10724834, 0.07715801, 0.23277558, 0.42656933, 0.90647232,
       0.66863514, 0.93736457, 0.74243942, 0.66723835, 0.44421873,
       0.95665971, 0.43144506, 0.033625  , 0.17749485, 0.9082217 ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)
# created an array with values between 1 and 26
# changed the array to 5 list with 5 values in each list

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2:,1:]
# selected the values from the 2nd row to the end and from the 2nd value the the end

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3][4]
# selected only the 4 value from the third row     

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[0:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4:]
# selected the 4th row, from the first value to the last in the list

array([[21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:,:]
# selected all of the 3rd row and 4th row

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)
#found the sum of the array

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)
#fount the standard deviation of the values

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=0)
#found the sum of the columns

array([55, 60, 65, 70, 75])

# Cheers!